config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  root 'posts#index'

  resources :posts do
    collection do
      get :search
  end

    resources :comments
     resources :charges
     resources :votes

  end

  resources :tags   do
    resources :posts
  end
 

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/fav.rb
class Fav < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  after_create :send_new_post_email
  has_many :comments, dependent: :destroy
  has_many :votes
  belongs_to :user
  has_attached_file :image,
  								styles: { thumb: "250x250>" },
  								storage: :s3,
  								s3_credentials: {
  									access_key_id: 'AKIAISJ3BURO2DLFVRKQ',
  									secret_access_key: Rails.application.secrets.secret_access_key
  								},
  								bucket: 'swagstagram'

  has_and_belongs_to_many :tags                

	def tag_names
	     tags.map{|tag| tag.name}.join(', ')
	end

	  def tag_names=(tag_names)
	  	self.tags = Tag.find_or_create_from_tag_names(tag_names)
	  end

	  def self.for_tag_or_all(tag_name)
	  	tag_name ? Tag.find_by(text: tag_name).posts : all
	  end

    def points
      votes.where(up: true).count - votes.where(up: false).count
    end

    def send_new_post_email
      PostMailer.new_post(self, user).deliver!
    end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	before_validation :format_name
	has_and_belongs_to_many :posts

	def to_s
		'#' + text
	end

	def to_param
  		text
  	end


  	def self.find_or_create_from_tag_names(tag_names)
  			tag_names.split(/,\s?/).map do |tag_name|
	  		find_or_create_by(text: tag_name)
	  	end
  	end

  	private

  	def format_name
  		self.text = text.downcase.gsub(/[^a-z]/, '')
  	end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

   has_many :posts



	def self.find_for_social_oauth(auth)
		pwd = Devise.friendly_token[0,20]
	  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	    user.provider = auth.provider
	    user.email = auth.info.email if auth.info.email
	    user.uid = auth.uid
	    user.password = pwd
	    user.save!
	  end
	end


	# def self.find_for_facebook_oauth(auth)
	# 	pwd = Devise.friendly_token[0,20]
	#   where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	#     user.provider = auth.provider
	#     user.uid = auth.uid
	#     user.password = pwd
	#     user.save!
	#   end
	# end

	def email_required?
		return false if provider 
		super
	end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



	def nag_for_email
		     if user_singed_in? && current_user.email.blank?
		flash[:error] = 'Please fill in your email'
				 end
	end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

before_filter :authenticate_user!

def create
  # Amount in cents
  @amount = 1500

  customer = Stripe::Customer.create(
    :email => current_user.email,
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'GBP'
  )

  	#below here
  flash[:notice] = 'Your payment was successful'
  redirect_to '/posts'

  	#email

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to '/posts'
end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params[:comment].permit(:text))
    @comment.post_id = @post.id
    @comment.user = current_user  
    # @post.comments << @comment

    if @comment.save
      redirect_to '/posts'
    else
      render 'new'
    end
  end


  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

	def twitter
		    # You need to implement the method below in your model (e.g. app/models/user.rb)
    social

    #twitter's devise documentation which we shortened

    # if @user.persisted?
    #   sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    #   # set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    # else
    #   session["devise.twitter_data"] = request.env["omniauth.auth"]
    #   redirect_to new_user_registration_url
    # end
	end

		def facebook
		    # You need to implement the method below in your model (e.g. app/models/user.rb)
		   social
	end

	private

	def social
		@user = User.find_for_social_oauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end

  # alias_method :twitter, :social
  # alias_method :facebook, :social

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :fetch_user_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :update]
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post].permit(:title, :content, :image, :tag_names))
    @post.user = current_user

    if @post.save
      redirect_to '/posts'
    else
      render 'new'
    end
  end

  def index
    @posts = Post.for_tag_or_all(params[:tag_id]).order('created_at DESC')
  end

  def edit
  end

  def update
    if @post.update(params[:post].permit(:title, :content, :image, :tag_names))
      redirect_to '/posts'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to '/posts'
  end

  def show
    @post = Post.find(params[:id])
  end

  def search
    # @post = post.where("title ILIKE '%?%'", params[:query])
    @posts = Post.where("title ILIKE ?", "%#{params[:query]}%")
    render 'index'
  end

  private

  def fetch_user_post
    @post = Post.find_by(id: params[:id], user: current_user)
    # @post = current_user.posts.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


	def create
		@post = Post.find(params[:post_id])
		Vote.create(up: params[:up], post: @post)

		# WebsocketRails[:votes].trigger 'new', { id: @post.id, points: @post }
		WebsocketRails[:votes].trigger 'update_vote', { id: @post.id, points: @post.points }

		redirect_to '/posts'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_comment.html.erb
<%= comment.text %>

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :text %>
  <%= f.text_area :text %>

  <%= f.submit %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container">
<nav class="navbar navbar" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Languatics</a>
  </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Destinations", "/posts"%></li>
            <li><%= link_to "Add destination", "/posts/new"  %></li> 

          </ul>


      <div class="navbar-form navbar-left" role="search">
        <%= form_tag search_posts_path, method: :get do %>
        <%= text_field_tag :query, nil, id: 'search', class: "form-control", placeholder:"Search Destinations" %>
        <% end %>
      </div>



    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">User <b class="caret"></b></a>
            <ul class="dropdown-menu">

              <% if user_signed_in? %>
                <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
                <li>
                <%= link_to('Login', new_user_session_path)  %>  
                </li>
              <% end %>
              <% if user_signed_in? %>
                <li>
                <%= link_to('Edit registration', edit_user_registration_path) %>
                </li>
              <% else %>
                <li>
                <%= link_to('Register', new_user_registration_path)  %>
                </li>
              <% end %>
            <% if !user_signed_in? %>
          <li><%= link_to user_omniauth_authorize_path(:twitter) do %><i class="fa fa-twitter fa-2x"></i>Sign in
          <% end %>
        </li>
    <% end %>
             </li>
             </ul> 
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Languatics Payments Page" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->
     <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
<%=render '/layouts/navigation'%>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

        </div><!--/span-->
      </div><!--/row-->

      <footer>
       <center> <p>&copy; Languatics Payments Page</p></center>

        <center>
        <style>.ig-b- { display: inline-block; }
.ig-b- img { visibility: hidden; }
.ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
.ig-b-v-24 { width: 137px; height: 24px; background: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24.png) no-repeat 0 0; }
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
.ig-b-v-24 { background-image: url(//badges.instagram.com/static/images/ig-badge-view-sprite-24@2x.png); background-size: 160px 178px; } }</style>
<a href="http://instagram.com/georgioboyy?ref=badge" class="ig-b- ig-b-v-24"><img src="//badges.instagram.com/static/images/ig-badge-view-24.png" alt="Instagram" /></a>
    </center>

      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/_post.html.erb
<div class='col-md-4 fonts'>
	<h1><%= link_to post.title, post_path(post), class: "fonts" %></h1>
	<div class="post-container">
		<div class="image">
	<%= image_tag post.image.url(:thumb), class: 'instagram-upload img-rounded img-reponsive' %></h1>
</div>
		<p><%= post.content %></p>

		<h3 class='votes_count' data-id='<%= post.id %>'><%= post.points %></h3>	

	<% if user_signed_in? %>
		<%= button_to 'Upvote', post_votes_path(post, up: true), remote: true %>
		<%= button_to 'Downvote', post_votes_path(post, up: false), remote: true %>	
	<% end %>

	<% if post.user == current_user %>
		<%= link_to 'Edit post', edit_post_path(post) %>
		<%= link_to 'Delete post', post_path(post), method: :delete %>
	<% end %>	

		<div class='tags'>
			<% post.tags.each do |tag| %>
		     <%= link_to tag, tag_posts_path(tag) %>
			<% end %>
		</div>

<%= link_to 'Add a comment', new_post_comment_path(post) %>
<br>
</div>


	<% if post.comments.any? %>
		<div class='post-comments'>
	<%= link_to 'Show comments', '#', data: { url: post_comments_path(post, format: :json) }, class: 'btn btn-success show-comments'%>
	<div class='spinner'>
		<img src='http://www.iab.net/extra/adquickref/spinnerLarge.gif'>
	</div>

	<script type='text/template', id='comment-template'>
		<div class ='well'>
			<h4>{{ commenter }}</h4>
			<p>{{ text }}</p>
		</div>
	</script>

		<div class='comments-container'></div>
		</div>
	<% end %>


</div>

		

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
						<div class='row'>

						<%= render @posts %>

						</div>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.label :tag_names, 'Tags' %>
  <%= f.text_area :tag_names, id: 'tag_input' %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<%= render @post.comments %>

<%= form_tag post_charges_path(@post) do %>

<h3>Buy this print</h3>
 <p>Bend in your pocket is only: £15.00</p>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.application.secrets[:stripe_publishable_key] %>"
          data-description="Print of <%= @post.title %>"
          data-amount="1500"
          data-currency="GBP"></script>

<% end %>